# Generated by Django 4.2.27 on 2025-12-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imovel',
            options={'verbose_name': 'Imóvel', 'verbose_name_plural': 'Imóveis'},
        ),
        migrations.AddField(
            model_name='imovel',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='status',
            field=models.CharField(choices=[('D', 'Disponível'), ('L', 'Alugado'), ('M', 'Manutenção/Limpeza')], default='D', max_length=1),
        ),
    ]
