# Generated by Django 4.2.27 on 2025-12-28 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_alter_imovel_options_imovel_descricao_imovel_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imovel',
            old_name='valor_aluguel',
            new_name='valor_diaria',
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('data_entrada', models.DateField()),
                ('data_saida', models.DateField()),
                ('valor_cobrado_diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imoveis.imovel')),
            ],
            options={
                'verbose_name': 'Locação',
                'verbose_name_plural': 'Locações',
            },
        ),
    ]
