# Generated by Django 4.2.27 on 2025-12-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_rename_valor_aluguel_imovel_valor_diaria_locacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao',
            name='cpf',
            field=models.CharField(default='000.000.000-00', max_length=14),
        ),
        migrations.AddField(
            model_name='locacao',
            name='telefone',
            field=models.CharField(default='(00) 00000-0000', max_length=20),
        ),
    ]
