# Generated by Django 4.2.27 on 2025-12-30 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0004_locacao_cpf_locacao_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Visualizar Relatório Gerencial',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='imovel',
            name='valor_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor de Compra/Investimento'),
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('CONDOMINIO', 'Condomínio'), ('IPTU', 'IPTU'), ('ENERGIA', 'Energia Elétrica'), ('INTERNET', 'Internet'), ('LIMPEZA', 'Limpeza/Lavanderia'), ('MANUTENCAO', 'Manutenção'), ('OUTROS', 'Outros')], max_length=20)),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateField(verbose_name='Data do Pagamento')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='imoveis.imovel')),
            ],
            options={
                'verbose_name_plural': 'Despesas',
            },
        ),
    ]
