# Generated by Django 4.2.27 on 2025-12-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaAdvocacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=200)),
                ('local', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('C', 'Custeio'), ('I', 'Investimento')], default='C', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Advocacia: Despesas',
            },
        ),
        migrations.CreateModel(
            name='FaturamentoAdvocacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('cliente', models.CharField(max_length=150)),
                ('documento', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Advocacia: Faturamentos',
            },
        ),
    ]
