# Generated by Django 4.2.27 on 2025-12-30 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advocacia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioAdvocacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Visualizar Relatório',
                'verbose_name_plural': 'Visualizar Relatórios',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='despesaadvocacia',
            options={'verbose_name': 'Despesa', 'verbose_name_plural': 'Despesas'},
        ),
        migrations.AlterModelOptions(
            name='faturamentoadvocacia',
            options={'verbose_name': 'Faturamento', 'verbose_name_plural': 'Faturamentos'},
        ),
        migrations.RemoveField(
            model_name='despesaadvocacia',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='faturamentoadvocacia',
            name='documento',
        ),
        migrations.AddField(
            model_name='faturamentoadvocacia',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='despesaadvocacia',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='despesaadvocacia',
            name='local',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='faturamentoadvocacia',
            name='cliente',
            field=models.CharField(max_length=255, verbose_name='Nome do Cliente'),
        ),
        migrations.CreateModel(
            name='ProcessoFaturamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=100, verbose_name='Processo')),
                ('competencia', models.CharField(max_length=100, verbose_name='Competência')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('baixado', 'Baixado')], default='ativo', max_length=10)),
                ('faturamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='advocacia.faturamentoadvocacia')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
            },
        ),
    ]
